Bunde20/Team-SCCRM-3

package-lock.json
package.json

deleted and reinstalled for a correct package and package-lock jsons

readjusted package-lock-json to attempt another merge

---

client/index.html
client/src/App.css
client/src/components/HomepageButton.jsx
client/src/components/Modal.jsx
client/src/pages/Homepage/Homepage.css
client/src/pages/Homepage/Homepage.jsx

- updated the buttons
- applied a font style across the website
- added game title to homepage

Homepage css 2

---

client/src/components/BackButton/BackButton.css
client/src/components/BackButton/BackButton.jsx
client/src/pages/Homepage/Homepage.css
client/src/pages/Lobby/Lobby.css
client/src/pages/Lobby/Lobby.jsx

applied a background and basic page layout to the lobby screen

added background and basic page layout to lobby

---

client/src/components/Card.css
client/src/components/MarketplaceNav.jsx
client/src/components/TradeOffer.jsx
client/src/main.jsx
client/src/pages/Deck/MyDeck.css
client/src/pages/Deck/MyDeck.jsx
client/src/pages/Marketplace/Marketplace.jsx
client/src/pages/Trade/Trade.css
client/src/pages/Trade/Trade.jsx

Set up marketplace nav with buy/trade/mydeck pages

Set up marketplace nav with buy/trade/mydeck pages

---

client/src/components/Card.css
client/src/components/Card.jsx
client/src/components/PurchaseBtn.jsx
client/src/pages/Marketplace/Marketplace.jsx
client/src/pages/Trade/Trade.jsx

Added css queries to handle card sizing changes on smaller screens

Added css queries to handle card sizing changes on smaller screens

---

client/src/components/Card.css

added gradient to cards and increased image size on large screen

added gradient to cards and increased image size on large screen

---

client/src/components/Card.css
client/src/components/Card.jsx
client/vite.config.js

Adjusted card styling for screen sizing

Adjusted card styling for screen sizing

---

client/src/pages/Homepage/Homepage.css
client/vite.config.js

Fixed target & adjusted hometitle for smaller screens

Fixed target & adjusted hometitle for smaller screens

---

client/src/components/BackButton/BackButton.jsx
client/src/components/CardSelectButton/CardSelectButton.jsx
client/src/components/CardSelectButton/index.css
client/src/pages/Lobby/Lobby.jsx

added click functionality to buttons and updated state array with ids

Array of card ids onclick

---

client/src/components/Card.css
client/src/components/TradeCarousel.jsx
client/src/components/TradeOffer.jsx
client/src/pages/Trade/Trade.css
client/src/pages/Trade/Trade.jsx

Changed trade offers to be included in a carousel component

Changed trade offers to be included in a carousel component

---

client/src/components/BeginButton.jsx
client/src/pages/Lobby/Lobby.css
client/src/pages/Lobby/Lobby.jsx
client/src/pages/Marketplace/Marketplace.jsx
client/src/pages/Tutorial/HowToPlay.jsx

we can set a team on lobby and fixed back to home buttons

Assign team onclick

---

client/src/pages/Lobby/Lobby.jsx
client/vite.config.js

removed div for cards in favor of highlighting them on click instead, as that will be a better UI experience

Lobby div removal

---

client/src/components/Timer/Timer.css
client/src/components/Timer/Timer.jsx
client/src/pages/Deck/MyDeck.jsx
client/src/pages/Marketplace/Marketplace.jsx

Styling changes & Added timer to reset marketplace cards

Styling changes & Added timer to reset marketplace cards

---

client/src/components/Card.css
client/src/pages/Lobby/Lobby.css
client/src/pages/Lobby/Lobby.jsx

Added a handler to update the team based on the cards chosen and highlight them so it is more intuitive for the users. I added an if statement to catch anyone trying to change their cards after selecting confirm. We can add a modal with more info for them later, but for now, I basically just disabled the ability to click so the user is no longer getting feedback and understands they need to proceed.

Onclick change lobby

---

client/src/components/Card.css

Reassigned the pointer-events: none styling to card container ONLY and now all the buttons should be working.

overassigned events none to button container as well

---

client/src/components/SeekCardBtn.jsx
client/src/components/createOfferModal.css
client/src/components/createOfferModal.jsx
client/src/components/createOfferModalBtn.jsx
client/src/pages/Marketplace/Marketplace.css

Added styling to seeking card modal/back button at the bottom

Added styling to seeking card modal/back button at the bottom

---

client/src/components/PurchaseBtn.jsx
client/src/components/createOfferBtn.jsx

Added margin bottoms to cards for spacing on smaller screens

Added margin bottoms to cards for spacing on smaller screens

---

client/src/components/CardSelectButton/CardSelectButton.jsx
client/src/components/CardSelectButton/index.css
client/src/pages/Homepage/Homepage.css
client/src/pages/Homepage/Homepage.jsx
client/src/pages/Lobby/Lobby.jsx
client/vite.config.js

I addressed some bugs I introduced while building out Lobby that affected the homepage.
- Homepage buttons (other than logout) were displaying too small
The Welcome message now only appears if you're logged in and it's styling has been updated.
Removed a deprecated component and its associated calls.

Welcome message toggle display

---

client/src/components/MarketplaceNav.jsx
client/vite.config.js

I updated the subtext in the marketplace to have slightly more space and larger font for better UI. 
Note to Steven: I don't want to step on toes, so if you hate this, revert it!

updated the 3 word links in marketplace

---

client/src/pages/Homepage/Homepage.jsx
client/src/pages/Lobby/Lobby.jsx

- used ternary operator for logout/login buttons
- removed console.logs from finished code

Homepage refactor

---

client/src/pages/Error404/Error.css
client/src/pages/Error404/Error.jsx
client/vite.config.js

404 error page stylize

---

client/src/components/Timer/index.jsx
client/src/components/Timer/style.css
client/src/pages/Marketplace/Marketplace.css
client/src/pages/Marketplace/Marketplace.jsx

Changed font for timer/coins on marketplace page

Changed font for timer/coins on marketplace page

---

client/src/pages/Lobby/Lobby.jsx

Changed lobby styling to display more cards on smaller screens

Changed lobby styling to display more cards on smaller screens

---

client/src/pages/Rewards/Rewards.jsx

I changed the image swap to utilize state as the on click event didn't seem to be working on the deployed site

rewards page image swap uses state now

---

client/src/main.jsx
client/src/pages/Error404/Error.jsx
client/src/pages/Lobby/Lobby.jsx
client/src/pages/Rewards/Rewards.jsx

Lobby:
- added padding on cards to prevent the highlighting from blurring together
- made line under Choose 3 cards no extend the whole length of the screen
Rewards:
- checks for playerVictory token, or moves user to the error page

updated lobby padding and added rewrds screen token validation

---

client/src/components/Card/index.jsx
client/src/components/Card/style.css
client/src/components/GameComponents/Boss.css
client/src/components/GameComponents/Boss.jsx
client/src/pages/Game/Game.css
client/src/pages/Game/Game.jsx

Styling for the game page to avoid scrolling

Styling for the game page to avoid scrolling

---

client/src/components/Buttons/LeaveRewardsButton/index.jsx
client/src/main.jsx
client/src/pages/Lobby/Lobby.jsx
client/src/pages/Rewards/Rewards.jsx
server/controllers/loginController.js
server/server.js

- removed pageLoad variable and just set the useEffect to empty array to load only once on Lobby and Rewards
- removed commented out code in main.jsx
- removed deprecated cookie code from server and loginController.js

refactored lobby/rewards and removed cookie from BE

---

client/src/components/Card/index.jsx
client/src/components/GameComponents/AttackSpecialBtn.jsx
client/src/components/GameComponents/Boss.css
client/src/components/GameComponents/Boss.jsx
client/src/components/Marketplace/PurchaseBtn/index.jsx
client/src/main.jsx
client/src/pages/Game/Game.css
client/src/pages/Game/Game.jsx
client/vite.config.js

Added battle styling for most screen sizes

Added battle styling for most screen sizes

---

client/src/pages/Game/Game.jsx

Remove extra p tag in game jsx

Remove extra p tag in game jsx

---

server/seed.js

swapped cdn provider for some of the images as a test. going to see if this resolves our card image issues

Fix cdn image

---

README.md
server/seed.js

To be more lore accurate:
- swapped varchar and growzilla
- swapped seasharp and swinteger
updated the remaining programon image links

removed discord cdn links and added remaining imagekit.io links
